#ifndef PRECOMPILEDHEADERS_QT3D
#define PRECOMPILEDHEADERS_QT3D

#include<QDebug>
#include <QtCore/QtCore>
#include <QtGui/QtGui>

#include <Qt3D/qabstractdownloadmanager.h>
#include <Qt3D/qareaallocator.h>
#include <Qt3D/qarray.h>
#include <Qt3D/qbox3d.h>
#include <Qt3D/qcolor4ub.h>
#include <Qt3D/qcustomdataarray.h>
#include <Qt3D/qdownloadmanager.h>
#include <Qt3D/qgeometrydata.h>
#include <Qt3D/qglabstracteffect.h>
#include <Qt3D/qglabstractmaterial.h>
#include <Qt3D/qglabstractscene.h>
#include <Qt3D/qglabstractsurface.h>
#include <Qt3D/qglattributedescription.h>
#include <Qt3D/qglattributeset.h>
#include <Qt3D/qglattributevalue.h>
#include <Qt3D/qglbezierpatches.h>
#include <Qt3D/qglbuilder.h>
#include <Qt3D/qglcamera.h>
#include <Qt3D/qglcameraanimation.h>
#include <Qt3D/qglcolladafxeffect.h>
#include <Qt3D/qglcolladafxeffectfactory.h>
#include <Qt3D/qglcolladafxeffectloader.h>
#include <Qt3D/qglcolormaterial.h>
#include <Qt3D/qglcube.h>
#include <Qt3D/qglcylinder.h>
#include <Qt3D/qgldome.h>
#include <Qt3D/qglframebufferobjectsurface.h>
#include <Qt3D/qglgraphicsviewportitem.h>
#include <Qt3D/qglindexbuffer.h>
#include <Qt3D/qgllightmodel.h>
#include <Qt3D/qgllightparameters.h>
#include <Qt3D/qglmaterial.h>
#include <Qt3D/qglmaterialcollection.h>
#include <Qt3D/qglnamespace.h>
#include <Qt3D/qglpainter.h>
#include <Qt3D/qglpicknode.h>
#include <Qt3D/qglpixelbuffersurface.h>
#include <Qt3D/qglrenderorder.h>
#include <Qt3D/qglrenderordercomparator.h>
#include <Qt3D/qglrendersequencer.h>
#include <Qt3D/qglrenderstate.h>
#include <Qt3D/qglsceneformatplugin.h>
#include <Qt3D/qglscenenode.h>
#include <Qt3D/qglshaderprogrameffect.h>
#include <Qt3D/qglsphere.h>
#include <Qt3D/qglsubsurface.h>
#include <Qt3D/qglteapot.h>
#include <Qt3D/qgltexture2d.h>
#include <Qt3D/qgltexturecube.h>
#include <Qt3D/qgltwosidedmaterial.h>
#include <Qt3D/qglvertexbundle.h>
#include <Qt3D/qglview.h>
#include <Qt3D/qglwidgetsurface.h>
#include <Qt3D/qgraphicsbillboardtransform.h>
#include <Qt3D/qgraphicsembedscene.h>
#include <Qt3D/qgraphicsrotation3d.h>
#include <Qt3D/qgraphicsscale3d.h>
#include <Qt3D/qgraphicstransform3d.h>
#include <Qt3D/qgraphicstranslation3d.h>
#include <Qt3D/qlogicalvertex.h>
#include <Qt3D/qmatrix4x4stack.h>
#include <Qt3D/qopenglfunctions.h>
#include <Qt3D/qplane3d.h>
#include <Qt3D/qray3d.h>
#include <Qt3D/qsphere3d.h>
#include <Qt3D/qt3dglobal.h>
#include <Qt3D/qtriangle3d.h>
#include <Qt3D/qvector2darray.h>
#include <Qt3D/qvector3darray.h>
#include <Qt3D/qvector4darray.h>

#endif